---
- hosts: uninitialized_beaglebone
  remote_user: debian

  vars:
    new_name: "oscilloscope-{{ansible_facts.machine_id[-4:]}}"

  tasks:
    - name: Initializing a new beaglebone board 
      debug: 
        msg: "{{ new_name }}"       
      tags: debug_info

    - name: change password for root user
      become: true
      user:
        name: debian
        # openssl passwd -salt bone -1 <plaintext>
        password: "$1$bone$RHLsnAT9n/CTsr9TWq8AA."

    - name: "change hostname to {{ new_name }}"
      become: true
      hostname:
        name: "{{ new_name }}"

    - name: Change hostname in /etc/hosts
      become: true
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost {{ new_name }}'
        state: present

    - name: "Reboot to trigger overlay changes."
      become: yes
      reboot:
        connect_timeout: 0
