---
- hosts: beaglebones
  remote_user: debian
  become: true

  tasks:
    - name: Enable the wifi adapter
      command: "connmanctl enable wifi"

    - name: Scan AP's
      command: "connmanctl scan wifi"

    - name: Scan AP's
      command: "connmanctl services"
      register: aps
    
    - debug: var=aps.stdout_lines

    - debug:
        msg: "Note the AP-identifier you would like to connect to above (formatted wifi_XXXXX_XXXXX)"
