---
- hosts: beaglebones
  remote_user: debian
  become: true
  
  vars_prompt:
    - name: "wifi_identifier"
      prompt: "What is the wifi identifier?"

    - name: "wifi_passphrase"
      prompt: "What is the passphrase for this AP?"
      private: yes

  tasks:
    - name: Enable the wifi adapter
      command: "connmanctl enable wifi"

    - name: Generic question with multiple different responses
      expect:
        command: "conmanctrl connect {{ wifi_identifier }}"
        responses:
          Question:
            - "{{ wifi_passphrase }}"
