---
- hosts: beaglebones
  remote_user: debian
  gather_facts: no

  tasks: 
    - name: "Get pip installer"
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: "/home/debian/get-pi.py"

    - name: "Python3 | Install pip3"
      command: python3 /home/debian/get-pi.py
      become: true

      args:
        creates: /usr/local/bin/pip3

    # Install numpy from apt (compiling takes forever)
    - name: "Python3 | Install numpy via apt"
      become: true
      apt:
        name: python3-numpy

    - name: "Python3 | libffi | Clone ffi package"
      git:
        clone: yes
        repo: 'https://github.com/libffi/libffi.git'
        dest: /home/debian/libffi

    # NOTE(meawoppl) - I have no idea why this requires shell
    - name: "Python3 | libffi | autotools"
      shell: "autoreconf -i"
      args:
        chdir: "/home/debian/libffi"

    - name: "Python3 | libffi | Configure"
      command: "./configure"
      args: 
        chdir: "/home/debian/libffi"

    - name: "Python3 | libffi | Hack to make libffi compile"
      lineinfile:
          regexp: "^MAKEINFO =*"
          line: "MAKEINFO = true"
          dest: "/home/debian/libffi/armv7l-unknown-linux-gnueabihf/doc/Makefile"  

    - name: "Python3 | libffi | make"
      make:
        chdir: /home/debian/libffi

    - name: "Python3 | libffi | make install"
      become: true
      make:
        chdir: /home/debian/libffi/
        target: install

    - name: "Python3 | Copy requirements.txt to remote host"
      copy:
        src: "../requirements.txt"
        dest: "/tmp/requirements.txt"
      register: info_requirements_file

    - name: "Python3 | Install python modules from requirements.txt"
      pip:
        requirements: "/tmp/requirements.txt"
        executable: pip3
