---
- hosts: beaglebones
  remote_user: debian
  tasks: 
  - name: "Boot Setup - Disable Video Overlay"
    lineinfile:
      line: "disable_uboot_overlay_video=1"
      dest: "/boot/uEnv.txt"
    become: yes

  - name: "Boot Setup - Enable PRU UIO"
    lineinfile:
      line: "uboot_overlay_pru=/lib/firmware/AM335X-PRU-UIO-00A0.dtbo"
      dest: "/boot/uEnv.txt"
    become: yes

  - name: "Boot Setup - Copy device tree overlay to host"
    copy:
      src: "../firmware/EBB-PRU-ADC.dts"
      dest: "/tmp/EBB-PRU-ADC.dts"

  - name: "Compile device tree overlay -> firmware folder"
    command: "dtc -o dtb -o /lib/firmware/EBB-PRU-ADC.dtbo -b 0 -@ /tmp/EBB-PRU-ADC.dts"
    become: yes

  - name: "Boot Setup - Setup overlay to load on next boot"
    lineinfile:
      line: "uboot_overlay_addr0=/lib/firmware/EBB-PRU-ADC.dtbo"
      dest: "/boot/uEnv.txt"
    become: yes
